language: node_js
node_js:
  - '6'
dist: trusty
addons:
  chrome: stable
cache:
  directories:
    - node_modules
env:
  global:
    # PUBLICA_NPM_TOKEN
    secure: "LqhhN8aMTrYNDD3LeASMIcpBov6DVClzPAjfx/mtyIgbRUTWT8dH6FwXc7/Az7ydvUp7NpGA5F+enpj3I6vmLDTWfRLvR+Vbv1bNLhqDp7RtQFjTYZsVKwA1eSFfvy2ykEtmnfGq88k6vnAmvzj/HcwMb/NWRYb9yBLJgux2on6dZCaRxCqkJ0WVZ806D+4mNqVi06kZu3u61z1CX5j9V75cUPPQcqAroNaxfut+0yvl9EjzNXRPhLKdZQpdt9E/EPbK+hnO4lzHVxChX59J9Dv/YGdc6RTxrAm2ePCKeQfdKLHJlV6txlU1JPsWfzCTdIoIywY1q00Wx7RHgsS7rq/Y2WafmDsZ3RRLo2qQXwKslhMw2CK09Pzq9N/64938g7vhTZfePLIKC3PYOalaQKC9U7riqS8VVzZR2k7O6OBUZKnk3XweMPJqPjp4iDOM0sQ32oJK8aE+bCa8PVxw1xEP9zqzv9HZqJ8RhdoedUx0I0bS5RLWrsr3QIw3pGpj64mNbF1Kx8p3WvovY+OjrMKocTKw2QVzNGXVvM++K6R/Xxt3+shnpVTFNmAAcO3yMDqMlrSBHE00JrfIapTSa8sgYUqTIS9Lt0RSDjQNTcLnxv3IxEKfWP+fTJBJpQaSkxnrEXpelEvZwAsLbzs25CXY/t32XUjmPXF/csiE73M="
notifications:
  slack:
    # publica, channel set by slack's integration setting for Travis-CI.
    secure: "P61hlWUPh6HUK6z+I2KNJdBuOADioLRtWoN+r0vhKgAmqvXE9S5x26us3bsYJ0MdWGXdFPQYqJ7OOLw2EkiuMP/vqBQ+b++voQbKo9qr1rk13hDIBHKCxeY6O5SH8uuc78+U36OT8Vb7vjqoprSI3RgzludKlIp2/OKokvVGueLNm3mCHgv/Grt1eLKG7KI+6CsxmshAKOoZWupSnwiI0FGW6DnKoNv9yzzSD5ZE1PQ5H46P5s4a3aMvQqgg8jWxhFFrvWBK6yk0QeonvPKLXn1VVjLQ2Ks1PNIugV9LkULudzV6OIq9m9uX7fPCTEkQT47eaWGw3VGDa6tjKnSl3NUpPw/+RxEAObxuGLGsMpfGpiSiCOGttFE38W8IYOLSHSDsfri30hmlVmutoToTjTZ56bd+Zvu2eaAchKyui0D2MqA5pUfzR7Coqh9zVf32MZ1Y0Wr3AnbQmBfR1/tGs6vyVAIGDnxwL2HNPJ5gvfNjfo6TyMY5rH1iig9lnIynLUrxltY7WrEnZX4wj4KBqZlhVPsEY1Zy4Ear5RQnnn8Kl60GNW3KuDXKeU+lai+T3qJfcGCGSpwq/veFdqo3GT7k4mipAU8UcQzmkEosna1Pf5FqGRilnLOykcggs9SJMiwHHiduoB5NNhAJCqflcPB4AvLZE+yW3VliLjxg8Js="
before_install:
  # Disable the spinner, it looks bad on Travis
  - npm config set spin false
  # Log HTTP requests
  - npm config set loglevel http
install:
  - npm install
script:
  - npm run build.prod
deploy:
  provider: npm
  email: "infra@publica-project.com"
  api_key: $PUBLICA_NPM_TOKEN
  skip_cleanup: true
  on:
    branch: master
